### ISSUE TITLE
ESP-IDF Manager: 'Installing tools...' has encountered a problem. Cannot invoke "String.indexOf(int)" because "value" is null (IEP-1317)

### ISSUE THREAD

**Issue by Abdull** [espressif/idf-eclipse-plugin#1040]
**Describe the bug**
In a freshly installed *Espressif IDE 3.0.0* (via `Espressif-IDE-3.0.0-linux.gtk.x86_64.tar.gz`), despite fulfilling all prerequisites and following the steps installations steps found in https://github.com/espressif/idf-eclipse-plugin/blob/27f07351f83acc220e4630d29120d2dd89a02c07/README.md#Installation , I cannot setup the ESP-IDF via the ESP-IDF Manager.

![image](https://github.com/user-attachments/assets/0dfb2707-2acd-4105-9a65-725ea85c4805)

Neither "*Use an existing ESP-IDF directory from file system*" (providing existing ESP-IDF directory `/opt/install/esp-idf`) nor "*Download ESP-IDF*" work. Both will eventually result in a "Problem Occured" modal with the error message:

> 'Installing tools...' has encountered a problem.
> Cannot invoke "String.indexOf(int)" because "value" is null

![Screenshot_20240827_182104](https://github.com/user-attachments/assets/4842188f-fbe8-42c5-b927-ff454e35a10a)

The Eclipse *Console* view has the following output:

<details>
  <summary>Eclipse *Console* output (click to expand)</summary>

```
Installing tools...
This can take a while. Please be patient.
Executing /usr/bin/python3.11 /opt/install/esp-idf/tools/idf_tools.py install all
Selected targets are: esp32, esp32c2, esp32p4, esp32s3, esp32h2, esp32c6, esp32c3, esp32c5, esp32s2, esp32c61
Current system platform: linux-amd64
Installing tools: xtensa-esp-elf-gdb, riscv32-esp-elf-gdb, xtensa-esp-elf, esp-clang, riscv32-esp-elf, esp32ulp-elf, cmake, openocd-esp32, ninja, esp-rom-elfs, qemu-xtensa, qemu-riscv32
Skipping xtensa-esp-elf-gdb@14.2_20240403 (already installed)
Skipping riscv32-esp-elf-gdb@14.2_20240403 (already installed)
Skipping xtensa-esp-elf@esp-13.2.0_20240530 (already installed)
Skipping esp-clang@esp-17.0.1_20240419 (already installed)
Skipping riscv32-esp-elf@esp-13.2.0_20240530 (already installed)
Skipping esp32ulp-elf@2.38_20240113 (already installed)
Skipping cmake@3.24.0 (already installed)
Skipping openocd-esp32@v0.12.0-esp32-20240726 (already installed)
Skipping ninja@1.11.1 (already installed)
Skipping esp-rom-elfs@20240305 (already installed)
Skipping qemu-xtensa@esp_develop_9.0.0_20240606 (already installed)
Skipping qemu-riscv32@esp_develop_9.0.0_20240606 (already installed)

Executing /usr/bin/python3.11 /opt/install/esp-idf/tools/idf_tools.py install-python-env
Python 3.11.2
pip 24.2 from /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages/pip (python 3.11)
Skipping the download of /home/abdull/.espressif/espidf.constraints.v5.4.txt because it was downloaded recently.
Upgrading pip and setuptools...
Looking in indexes: https://pypi.org/simple, https://dl.espressif.com/pypi
Requirement already satisfied: pip in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (24.2)
Requirement already satisfied: setuptools in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (71.0.0)
Installing Python packages
 Constraint file: /home/abdull/.espressif/espidf.constraints.v5.4.txt
 Requirement files:
  - /opt/install/esp-idf/tools/requirements/requirements.core.txt
Looking in indexes: https://pypi.org/simple, https://dl.espressif.com/pypi, https://dl.espressif.com/pypi
Ignoring importlib_metadata: markers 'python_version < "3.8"' don't match your environment
Requirement already satisfied: setuptools in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from -r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 3)) (71.0.0)
Requirement already satisfied: packaging in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from -r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 4)) (24.1)
Requirement already satisfied: click in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from -r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 7)) (8.1.7)
Requirement already satisfied: pyserial in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from -r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 8)) (3.5)
Requirement already satisfied: cryptography in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from -r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 9)) (43.0.0)
Requirement already satisfied: pyparsing in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from -r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 10)) (3.1.4)
Requirement already satisfied: pyelftools in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from -r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 11)) (0.31)
Requirement already satisfied: idf-component-manager in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from -r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 12)) (2.0.3)
Requirement already satisfied: esp-coredump in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from -r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 13)) (1.11.0)
Requirement already satisfied: esptool in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from -r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 14)) (4.8.dev5)
Requirement already satisfied: esp-idf-kconfig in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from -r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 15)) (2.3.0)
Requirement already satisfied: esp-idf-monitor in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from -r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 16)) (1.4.0)
Requirement already satisfied: esp-idf-nvs-partition-gen in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from -r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 17)) (0.1.2)
Requirement already satisfied: esp-idf-size in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from -r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 18)) (1.5.0)
Requirement already satisfied: esp-idf-panic-decoder in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from -r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 19)) (1.1.0)
Requirement already satisfied: pyclang in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from -r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 20)) (0.4.2)
Requirement already satisfied: construct in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from -r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 21)) (2.10.70)
Requirement already satisfied: freertos_gdb in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from -r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 24)) (1.0.3)
Requirement already satisfied: cffi>=1.12 in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from cryptography->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 9)) (1.17.0)
Requirement already satisfied: colorama in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from idf-component-manager->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 12)) (0.4.6)
Requirement already satisfied: pyyaml in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from idf-component-manager->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 12)) (6.0.2)
Requirement already satisfied: requests in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from idf-component-manager->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 12)) (2.32.3)
Requirement already satisfied: requests-file in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from idf-component-manager->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 12)) (2.1.0)
Requirement already satisfied: requests-toolbelt in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from idf-component-manager->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 12)) (1.0.0)
Requirement already satisfied: tqdm in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from idf-component-manager->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 12)) (4.66.5)
Requirement already satisfied: jsonref in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from idf-component-manager->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 12)) (1.1.0)
Requirement already satisfied: pydantic in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from idf-component-manager->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 12)) (2.8.2)
Requirement already satisfied: pydantic-core in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from idf-component-manager->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 12)) (2.20.1)
Requirement already satisfied: pydantic-settings in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from idf-component-manager->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 12)) (2.4.0)
Requirement already satisfied: typing-extensions in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from idf-component-manager->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 12)) (4.12.2)
Requirement already satisfied: pygdbmi>=0.9.0.2 in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from esp-coredump->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 13)) (0.11.0.0)
Requirement already satisfied: bitstring>=3.1.6 in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from esptool->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 14)) (4.2.3)
Requirement already satisfied: ecdsa>=0.16.0 in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from esptool->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 14)) (0.19.0)
Requirement already satisfied: reedsolo<1.8,>=1.5.3 in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from esptool->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 14)) (1.7.0)
Requirement already satisfied: intelhex in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from esptool->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 14)) (2.3.0)
Requirement already satisfied: argcomplete>=3 in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from esptool->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 14)) (3.5.0)
Requirement already satisfied: rich in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from esp-idf-size->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 18)) (13.7.1)
Requirement already satisfied: bitarray<3.0.0,>=2.9.0 in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from bitstring>=3.1.6->esptool->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 14)) (2.9.2)
Requirement already satisfied: pycparser in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from cffi>=1.12->cryptography->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 9)) (2.22)
Requirement already satisfied: six>=1.9.0 in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from ecdsa>=0.16.0->esptool->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 14)) (1.16.0)
Requirement already satisfied: annotated-types>=0.4.0 in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from pydantic->idf-component-manager->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 12)) (0.7.0)
Requirement already satisfied: python-dotenv>=0.21.0 in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from pydantic-settings->idf-component-manager->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 12)) (1.0.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from requests->idf-component-manager->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 12)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from requests->idf-component-manager->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 12)) (3.8)
Requirement already satisfied: urllib3<3,>=1.21.1 in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from requests->idf-component-manager->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 12)) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from requests->idf-component-manager->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 12)) (2024.7.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from rich->esp-idf-size->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 18)) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from rich->esp-idf-size->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 18)) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in /home/abdull/.espressif/python_env/idf5.4_py3.11_env/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich->esp-idf-size->-r /opt/install/esp-idf/tools/requirements/requirements.core.txt (line 18)) (0.1.2)

Executing /usr/bin/python3.11 /opt/install/esp-idf/tools/idf_tools.py export --format=key-value
Executing null/bin/python /opt/install/esp-idf/tools/idf.py --version
Executing null/bin/python /opt/install/esp-idf/tools/idf.py --list-targets
```

</details>

Notice the last couple of lines:

```
# ...

Executing /usr/bin/python3.11 /opt/install/esp-idf/tools/idf_tools.py export --format=key-value
Executing null/bin/python /opt/install/esp-idf/tools/idf.py --version
Executing null/bin/python /opt/install/esp-idf/tools/idf.py --list-targets

```

**Notice the nonsensical executable path `null/bin/python`.** 

* For Git path, I use the prepopulated `/usr/bin/git` (which indeed is the correct path)
* For Python path, prepopulated `/home/abdull/.espressif/python_env/idf5.4_py3.11_env/bin/python3` does indeed exist (I don't know which tool prepared the `$HOME/.espressif/` directory structure, but it does include `./python_env/idf5.4_py3.11_env/bin/python3`, which is a symlink to `/usr/bin/python3`, which in turn is a symlink to `python3.11`, which in turn exists on my system (i.e., at `/usr/bin/python3.11`) ). 

**To Reproduce**
1. Download `Espressif-IDE-3.0.0-linux.gtk.x86_64.tar.gz` and extract. Start by executing command `./espressif-ide`
2. Close *Welcome* message
3. Open ESP-IDF Manager
4. Click "Add ESP-IDF"

**Expected behavior**
Specified ESP-IDF shall be added to *ESP-IDF Manager*'s  *IDF Tools* list. But actually isn't.

**Screenshots**
See inline.

**Espressif-IDE Product Information:**
Espressif > Product Information (Copy content from the console and attach as a file)

As the output includes too much sensitive information, please let me know which data in particular is required, and I'll update

```
* xtensa-esp-elf-gdb: GDB for Xtensa
  - 14.2_20240403 (recommended, installed)
* riscv32-esp-elf-gdb: GDB for RISC-V
  - 14.2_20240403 (recommended, installed)
* xtensa-esp-elf: Toolchain for 32-bit Xtensa based on GCC
  - esp-13.2.0_20240530 (recommended, installed)
* esp-clang: Toolchain for all Espressif chips based on clang (optional)
  - esp-17.0.1_20240419 (recommended, installed)
* riscv32-esp-elf: Toolchain for 32-bit RISC-V based on GCC
  - esp-13.2.0_20240530 (recommended, installed)
* esp32ulp-elf: Toolchain for ESP32 ULP coprocessor
  - 2.38_20240113 (recommended, installed)
* cmake: CMake build system (optional)
  - 3.24.0 (recommended, installed)
  - 3.16.3 (supported)
* openocd-esp32: OpenOCD for ESP32
  - v0.12.0-esp32-20240726 (recommended, installed)
* ninja: Ninja build system (optional)
  - 1.11.1 (recommended, installed)
* esp-rom-elfs: ESP ROM ELFs
  - 20240305 (recommended, installed)
* qemu-xtensa: QEMU for Xtensa (optional)
  - esp_develop_9.0.0_20240606 (recommended, installed)
* qemu-riscv32: QEMU for RISC-V (optional)
  - esp_develop_9.0.0_20240606 (recommended, installed)
OK

# truncated due to sensitive details
```

**Eclipse Error log:** 
Window > Show View > Other > Search for "Error Log" (Attach as a file)

Please attach the error log as described here https://github.com/espressif/idf-eclipse-plugin#error-log 

Because of sensitive data, adding the interesting bits here instead:

```
# ...

!ENTRY com.espressif.idf.core 4 0 2024-08-27 19:26:46.954
!MESSAGE Cannot run program "null/bin/python" (in directory "/"): error=2, No such file or directory
!STACK 0
java.io.IOException: Cannot run program "null/bin/python" (in directory "/"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.espressif.idf.core.ProcessBuilderFactory.run(ProcessBuilderFactory.java:42)
	at com.espressif.idf.ui.tools.ToolsJob.runCommandIdfPyInIdfEnv(ToolsJob.java:359)
	at com.espressif.idf.ui.tools.ToolsJob.getIdfVersionFromIdfPy(ToolsJob.java:310)
	at com.espressif.idf.ui.tools.ToolsJob.processExportCmdOutput(ToolsJob.java:121)
	at com.espressif.idf.ui.tools.ToolsInstallationJob.run(ToolsInstallationJob.java:78)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 7 more

# ...

!ENTRY com.espressif.idf.core 4 0 2024-08-27 19:26:46.965
!MESSAGE Cannot invoke "String.indexOf(int)" because "value" is null
!STACK 0
java.lang.NullPointerException: Cannot invoke "String.indexOf(int)" because "value" is null
	at java.base/java.lang.ProcessEnvironment.validateValue(ProcessEnvironment.java:120)
	at java.base/java.lang.ProcessEnvironment$Value.valueOf(ProcessEnvironment.java:203)
	at java.base/java.lang.ProcessEnvironment$StringEnvironment.put(ProcessEnvironment.java:243)
	at java.base/java.lang.ProcessEnvironment$StringEnvironment.put(ProcessEnvironment.java:221)
	at java.base/java.util.AbstractMap.putAll(AbstractMap.java:281)
	at com.espressif.idf.core.ProcessBuilderFactory.run(ProcessBuilderFactory.java:38)
	at com.espressif.idf.ui.tools.ToolsJob.runCommandIdfPyInIdfEnv(ToolsJob.java:359)
	at com.espressif.idf.ui.tools.ToolsJob.loadTargetsAvailableFromIdfInCurrentToolSet(ToolsJob.java:164)
	at com.espressif.idf.ui.tools.ToolsInstallationJob.run(ToolsInstallationJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY com.espressif.idf.core 4 0 2024-08-27 19:26:46.968
!MESSAGE Cannot invoke "String.indexOf(int)" because "value" is null
!STACK 0
java.lang.NullPointerException: Cannot invoke "String.indexOf(int)" because "value" is null
	at java.base/java.lang.ProcessEnvironment.validateValue(ProcessEnvironment.java:120)
	at java.base/java.lang.ProcessEnvironment$Value.valueOf(ProcessEnvironment.java:203)
	at java.base/java.lang.ProcessEnvironment$StringEnvironment.put(ProcessEnvironment.java:243)
	at java.base/java.lang.ProcessEnvironment$StringEnvironment.put(ProcessEnvironment.java:221)
	at java.base/java.util.AbstractMap.putAll(AbstractMap.java:281)
	at com.espressif.idf.core.ProcessBuilderFactory.run(ProcessBuilderFactory.java:38)
	at com.espressif.idf.ui.tools.ToolsJob.runCommandIdfPyInIdfEnv(ToolsJob.java:359)
	at com.espressif.idf.ui.tools.ToolsJob.loadTargetsAvailableFromIdfInCurrentToolSet(ToolsJob.java:164)
	at com.espressif.idf.ui.tools.ToolsInstallationJob.run(ToolsInstallationJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by Abdull** [comment]
OP here. I can happily report that this issue fixed itself. When I just retried adding ESP-IDFs in my Espressif IDE installation, it just worked.

Both "use an existing ESP-IDF directory from file system" and "download ESP-IDF" worked.

The only things that have changed or were done *from my side* since I reported this issue were reboots.

* Tested successfully with *all* ESP-IDF plugins at version `1.0.1.202408211148`. 
* Also tested successfully with *ESP-IDF SDK Config Core* (`com.espressif.idf.sdk.config.core`) at version `1.0.2.202408291042`.

I therefore close this issue. Feel free to reopen it if needed.

**Comment by lbthomsen** [comment]
I am still seeing this issue with latest versions everywhere.

**Comment by komcconnell** [comment]
Happening with me too. (Mac OSX Sonoma).

**Comment by alirana01** [comment]
Hi @komcconnell can you test it with the latest nightly build of the espressif-ide. This is planned for the upcoming release the nightly should contain the fix for this.

**Comment by lbthomsen** [comment]
> Hi @komcconnell can you test it with the latest nightly build of the espressif-ide. This is planned for the upcoming release the nightly should contain the fix for this.

See my comment in #1073 - nightly build as of a few days ago - still failing.

**Comment by Manikanta25055** [comment]
me too, I am also facing the same issue

**Comment by flodmotorgrodan** [comment]
This problem may be related to https://github.com/espressif/idf-eclipse-plugin/issues/1105#issuecomment-2666747708

Where idf_tools.py does not export the path to the ESP-IDF virtual python environment.

**Comment by rtek1000** [comment]
I just got this notice. Shouldn't it have been resolved?
