### ISSUE TITLE
JSON configuration server not starting: error is: InvocationTargetException (IEP-610)

### ISSUE THREAD

**Issue by MatthiasThoemel** [espressif/idf-eclipse-plugin#429]
If you run JAVA-17 with Eclipse 2021, all Plugins up to date (also those from Espressif) and you double click the sdkconfig file in the project explorer, the JSON config server does not start. 

In the Event log you see an InvocationTargetException and a JAVA callstack:

java.lang.reflect.InvocationTargetException
	at com.espressif.idf.sdk.config.ui.SDKConfigurationEditor.lambda$0(SDKConfigurationEditor.java:176)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
Caused by: java.lang.NullPointerException
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1092)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.espressif.idf.sdk.config.core.server.JsonConfigServer.start(JsonConfigServer.java:124)
	at com.espressif.idf.sdk.config.core.server.ConfigServerManager.getServer(ConfigServerManager.java:44)
	at com.espressif.idf.sdk.config.ui.SDKConfigurationEditor.initConfigServer(SDKConfigurationEditor.java:371)
	at com.espressif.idf.sdk.config.ui.SDKConfigurationEditor.lambda$0(SDKConfigurationEditor.java:171)
	... 1 more
Root exception:
java.lang.NullPointerException
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1092)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.espressif.idf.sdk.config.core.server.JsonConfigServer.start(JsonConfigServer.java:124)
	at com.espressif.idf.sdk.config.core.server.ConfigServerManager.getServer(ConfigServerManager.java:44)
	at com.espressif.idf.sdk.config.ui.SDKConfigurationEditor.initConfigServer(SDKConfigurationEditor.java:371)
	at com.espressif.idf.sdk.config.ui.SDKConfigurationEditor.lambda$0(SDKConfigurationEditor.java:171)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)

Here are the session data:
eclipse.buildId=4.22.0.I20211124-1800
java.version=17.0.1
java.vendor=Private Build
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.embedcpp.product -vm /usr/lib/jvm/java-17-openjdk-amd64/bin/
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.embedcpp.product -vm /usr/lib/jvm/java-17-openjdk-amd64/bin/

**Expected behavior**
it should work like in the Eclipse 2019-12 

**Environment Information:** 
[eclipse-config.txt](https://github.com/espressif/idf-eclipse-plugin/files/7799119/eclipse-config.txt)

**ESP-IDF Tools Information:**
Executing python /home/itsonix/ITSonix/ESP-IDF/esp-idf-v4.3.1/tools/idf_tools.py list
* xtensa-esp32-elf: Toolchain for Xtensa (ESP32) based on GCC
  - esp-2021r1-8.4.0 (recommended, installed)
* xtensa-esp32s2-elf: Toolchain for Xtensa (ESP32-S2) based on GCC
  - esp-2021r1-8.4.0 (recommended, installed)
* xtensa-esp32s3-elf: Toolchain for Xtensa (ESP32-S3) based on GCC
  - esp-2021r1-8.4.0 (recommended, installed)
* riscv32-esp-elf: Toolchain for 32-bit RISC-V based on GCC
  - esp-2021r1-8.4.0 (recommended, installed)
* esp32ulp-elf: Toolchain for ESP32 ULP coprocessor
  - 2.28.51-esp-20191205 (recommended, installed)
* esp32s2ulp-elf: Toolchain for ESP32-S2 ULP coprocessor
  - 2.28.51-esp-20191205 (recommended, installed)
* cmake: CMake build system (optional)
  - 3.16.4 (recommended, installed)
* openocd-esp32: OpenOCD for ESP32
  - v0.10.0-esp32-20210401 (recommended, installed)
* ninja: Ninja build system (optional)
  - 1.10.2 (recommended, installed)

**IDF Eclipse Plugin Version:** 
ESP-IDF Eclipse Plugin
Version: 2.3.0.202111091633
Copyright (c) 2021 ESPRESSIF SYSTEMS (SHANGHAI) CO., LTD. All rights reserved.

**Comment by MatthiasThoemel** [comment]
Here is some additional information:

Executing python /home/itsonix/ITSonix/ESP-IDF/esp-idf-v4.3.1/tools/idf_tools.py list
* xtensa-esp32-elf: Toolchain for Xtensa (ESP32) based on GCC
  - esp-2021r1-8.4.0 (recommended, installed)
* xtensa-esp32s2-elf: Toolchain for Xtensa (ESP32-S2) based on GCC
  - esp-2021r1-8.4.0 (recommended, installed)
* xtensa-esp32s3-elf: Toolchain for Xtensa (ESP32-S3) based on GCC
  - esp-2021r1-8.4.0 (recommended, installed)
* riscv32-esp-elf: Toolchain for 32-bit RISC-V based on GCC
  - esp-2021r1-8.4.0 (recommended, installed)
* esp32ulp-elf: Toolchain for ESP32 ULP coprocessor
  - 2.28.51-esp-20191205 (recommended, installed)
* esp32s2ulp-elf: Toolchain for ESP32-S2 ULP coprocessor
  - 2.28.51-esp-20191205 (recommended, installed)
* cmake: CMake build system (optional)
  - 3.16.4 (recommended, installed)
* openocd-esp32: OpenOCD for ESP32
  - v0.10.0-esp32-20210401 (recommended, installed)
* ninja: Ninja build system (optional)
  - 1.10.2 (recommended, installed)

IDF_PATH: /home/itsonix/ITSonix/ESP-IDF/esp-idf-v4.3.1
IDF_PYTHON_ENV_PATH: <NOT FOUND>
PATH: <NOT FOUND>

Operating System: linux
Java Runtime Version: 17.0.1+12-Ubuntu-120.04
Eclipse Version: 4.22.0.v20211124-1800
Eclipse CDT Version: 10.5.0.202109270023
IDF Eclipse Plugin Version: 2.3.0.202110080828
ESP-IDF version cannot be checked. IDF_PATH or IDF_PYTHON_ENV_PATH  are not set.
Python set for IDF_PYTHON_ENV: <NOT FOUND>
Python declared in PATH variable: Python 3.8.10

I am wondering why the IDF_PATH is not set. Maybe because I selected a present IDF installation at the tool setup instead of downloading a new IDF. Might that be the reason?

**Comment by MatthiasThoemel** [comment]
I solved the problem: one has to set the following environment variable in the Preferences->C++->Build->Envirnoment by hand:

IDF_PYTHON_ENV_PATH = <.espressif-location>/python_env/idf4.3_py3.8_env
