### ISSUE TITLE
Errors occur while trying to flash with eclipse plugin (IEP-727)

### ISSUE THREAD

**Issue by mickpf** [espressif/idf-eclipse-plugin#558]
Hello,

I use the latest ESP-IDF v4.4.1 under Ubuntu-MATE 22.04. Few days ago I installed Eclipse CDT 2022-06 and the IDF Eclipse Plugin 2.5.0.2206080313. My user is a member of system groups "dialout" and "plugdev".
I've setup a new project for esp32s3. When I try to flash, I get/see two errors:

1. the command line for flashing has a syntax error. It is said
`esptool.py esp32s3 -p /dev/ttyUSB0 -b 460800 --before=default_reset --after=hard_reset write_flash --flash_mode dio --flash_freq 80m  --flash_size 8MB 0x0 bootloader/bootloader.bin 0x10000 Clock.bin 0x8000 partition_table/partition-table.bin 0xd000 ota_data_initial bin 0x110000 resources.bin
`
but it should be
`esptool.py --chip esp32s3 -p /dev/ttyUSB0 -b 460800 --before=default_reset --after=hard_reset write_flash --flash_mode dio --flash_freq 80m  --flash_size 8MB 0x0 bootloader/bootloader.bin 0x10000 Clock.bin 0x8000 partition_table/partition-table.bin 0xd000 ota_data_initial bin 0x110000 resources.bin
`

Here the mandatory option name "--chip" is missing!

2. The flashing command displays missing permissions to the device /dev/ttyUSB0
```
[1102/1103] cd /opt/ESP32/v4.4.1/esp-idf/components/esptool_py && /opt/ESP32/v4.4.1/tools/cmake/3.20.3/bin/cmake -DIDF_PATH="/opt/ESP32/v4.4.1/esp-idf" -D SERIAL_TOOL="/opt/ESP32/v4.4.1/python_env/idf4.4_py3.10_env/bin/python /opt/ESP32/v4.4.1/esp-idf/components/esptool_py/esptool/esptool.py --chip esp32s3" -D SERIAL_TOOL_ARGS="--before=default_reset --after=hard_reset write_flash @flash_args "-D WORKING_DIRECTORY="/home/mick/Projects/ESP32/Clock/build" -P /opt/ESP32/v4.4.1/esp-idf/components/esptool_py/run_serial_tool.cmake
esptool.py esp32s3 -p /dev/ttyUSB0 -b 460800 --before=default_reset --after=hard_reset write_flash --flash_mode dio --flash_freq 80m --flash_size 8MB 0x0 bootloader/bootloader.bin 0x10000 Clock.bin 0x8000 partition_table/partition-table.bin 0xd000 ota_data_initial.bin 0x110000 resources.bin
esptool.py v3.3.1-dev
Serial port /dev/ttyUSB0
Traceback (most recent call last):
  File "/opt/ESP32/v4.4.1/python_env/idf4.4_py3.10_env/lib/python3.10/site-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
PermissionError: [Errno 13] Permission denied: '/dev/ttyUSB0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ESP32/v4.4.1/esp-idf/components/esptool_py/esptool/esptool.py", line 5387, in <module>
    _main()
  File "/opt/ESP32/v4.4.1/esp-idf/components/esptool_py/esptool/esptool.py", line 5380, in _main
    main()
  File "/opt/ESP32/v4.4.1/esp-idf/components/esptool_py/esptool/esptool.py", line 4687, in main
    esp = esp or get_default_connected_device(ser_list, port=args.port, connect_attempts=args.connect_attempts,
  File "/opt/ESP32/v4.4.1/esp-idf/components/esptool_py/esptool/esptool.py", line 114, in get_default_connected_device
    _esp = chip_class(each_port, initial_baud, trace)
  File "/opt/ESP32/v4.4.1/esp-idf/components/esptool_py/esptool/esptool.py", line 320, in __init__
    self._port = serial.serial_for_url(port)
  File "/opt/ESP32/v4.4.1/python_env/idf4.4_py3.10_env/lib/python3.10/site-packages/serial/__init__.py", line 90, in serial_for_url
    instance.open()
  File "/opt/ESP32/v4.4.1/python_env/idf4.4_py3.10_env/lib/python3.10/site-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 13] could not open port /dev/ttyUSB0: [Errno 13] Permission denied: '/dev/ttyUSB0'
CMake Error at run_serial_tool.cmake:56 (message):
  /opt/ESP32/v4.4.1/python_env/idf4.4_py3.10_env/bin/python
  /opt/ESP32/v4.4.1/esp-idf/components/esptool_py/esptool/esptool.py --chip
  esp32s3 failed


FAILED: CMakeFiles/flash 
cd /opt/ESP32/v4.4.1/esp-idf/components/esptool_py && /opt/ESP32/v4.4.1/tools/cmake/3.20.3/bin/cmake -D IDF_PATH="/opt/ESP32/v4.4.1/
esp-idf" -D SERIAL_TOOL="/opt/ESP32/v4.4.1/python_env/idf4.4_py3.10_env/bin/python /opt/ESP32/v4.4.1/esp-idf/components/esptool_py/e
sptool/esptool.py --chip esp32s3" -D SERIAL_TOOL_ARGS="--before=default_reset --after=hard_reset write_flash @flash_args" -D WORKING
_DIRECTORY="/home/mick/Projects/ESP32/Clock/build" -P /opt/ESP32/v4.4.1/esp-idf/components/esptool_py/run_serial_tool.cmake
ninja: build stopped: subcommand failed.
ninja failed with exit code 1
```
even though they are correct:
```
mick@~/Projects/ESP32/Clock/build:170$ ll /dev/ttyUSB0 
crw-rw---- 1 root dialout 188, 0 Jun 25 13:00 /dev/ttyUSB0
mick@~/Projects/ESP32/Clock/build:172$ grep mick /etc/group
adm:x:4:syslog,mick
dialout:x:20:mick
fax:x:21:mick
cdrom:x:24:mick
floppy:x:25:mick
tape:x:26:mick
sudo:x:27:mick
dip:x:30:mick
video:x:44:mick
plugdev:x:46:mick
lpadmin:x:121:mick
lxd:x:135:mick
mick:x:1000:
sambashare:x:136:mick

```
Kind Regards,
Michael

**Comment by mickpf** [comment]
After reboot it seems to work. The difference to the previous scenario: I've connected the device before starting eclipse!
Maybe this permission error occurs when you connect the ESP32 device after eclipse start!
