### ISSUE TITLE
Cannot finish tools installation in eclipse/Espressif-ide (IEP-829)

### ISSUE THREAD

**Issue by jotisk** [espressif/idf-eclipse-plugin#659]
**Describe the bug**
Tried all possible combination but still stucked at this point:

Python 3.9.16
pip 22.3.1 from C:\Espressif\python_env\idf4.3_py3.9_env\lib\site-packages\pip (python 3.9)

Requirement already satisfied: pip in c:\espressif\python_env\idf4.3_py3.9_env\lib\site-packages (22.3.1)
Requirement already satisfied: setuptools in c:\espressif\python_env\idf4.3_py3.9_env\lib\site-packages (65.6.3)
WARNING: Download failure HTTP Error 404: Not Found
Upgrading pip and setuptools...
Downloading https://dl.espressif.com/dl/esp-idf/espidf.constraints.v4.3.txt
Destination: C:\Espressif\espidf.constraints.v4.3.txt.tmp
WARNING: Failed to download https://dl.espressif.com/dl/esp-idf/espidf.constraints.v4.3.txt to C:\Espressif\espidf.constraints.v4.3.txt.tmp
WARNING: Download failure HTTP Error 404: Not Found
Downloading https://dl.espressif.com/dl/esp-idf/espidf.constraints.v4.3.txt
Destination: C:\Espressif\espidf.constraints.v4.3.txt.tmp
WARNING: Failed to download https://dl.espressif.com/dl/esp-idf/espidf.constraints.v4.3.txt to C:\Espressif\espidf.constraints.v4.3.txt.tmp
WARNING: Download failure HTTP Error 404: Not Found
Downloading https://dl.espressif.com/dl/esp-idf/espidf.constraints.v4.3.txt
Destination: C:\Espressif\espidf.constraints.v4.3.txt.tmp
WARNING: Failed to download https://dl.espressif.com/dl/esp-idf/espidf.constraints.v4.3.txt to C:\Espressif\espidf.constraints.v4.3.txt.tmp
ERROR: Failed to download, and retry count has expired
See the help on how to disable constraints in order to work around this issue.
Traceback (most recent call last):
  File "C:\Espressif\frameworks\esp-idf-v5.0\tools\idf_tools.py", line 2529, in <module>
    main(sys.argv[1:])
  File "C:\Espressif\frameworks\esp-idf-v5.0\tools\idf_tools.py", line 2521, in main
    action_func(args)
  File "C:\Espressif\frameworks\esp-idf-v5.0\tools\idf_tools.py", line 2020, in action_install_python_env
    constraint_file = get_constraints(idf_version)
  File "C:\Espressif\frameworks\esp-idf-v5.0\tools\idf_tools.py", line 1908, in get_constraints
    raise DownloadError()
__main__.DownloadError

Executing C:\Users\User\AppData\Local\Programs\Python\Python39\python.exe C:\Espressif\frameworks\esp-idf-v5.0\tools\idf_tools.py export --format=key-value
Traceback (most recent call last):
  File "C:\Espressif\frameworks\esp-idf-v5.0\tools\idf_tools.py", line 2529, in <module>
    main(sys.argv[1:])
  File "C:\Espressif\frameworks\esp-idf-v5.0\tools\idf_tools.py", line 2521, in main
    action_func(args)
  File "C:\Espressif\frameworks\esp-idf-v5.0\tools\idf_tools.py", line 1529, in action_export
    tools_info = load_tools_info()
  File "C:\Espressif\frameworks\esp-idf-v5.0\tools\idf_tools.py", line 1213, in load_tools_info
    return parse_tools_info_json(tools_info)  # type: ignore
  File "C:\Espressif\frameworks\esp-idf-v5.0\tools\idf_tools.py", line 1231, in parse_tools_info_json
    tool = IDFTool.from_json(tool_dict)
  File "C:\Espressif\frameworks\esp-idf-v5.0\tools\idf_tools.py", line 854, in from_json
    raise RuntimeError('supported_targets for tool %s is not a list of strings' % tool_name)
RuntimeError: supported_targets for tool xtensa-esp32-elf is not a list of strings
Executing C:\Users\User\AppData\Local\Programs\Python\Python39\python.exe -m pip install websocket-client
Requirement already satisfied: websocket-client in c:\users\user\appdata\local\programs\python\python39\lib\site-packages (1.4.2)
WARNING: You are using pip version 22.0.4; however, version 22.3.1 is available.
You should consider upgrading via the 'C:\Users\User\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.
Operations completed!

**To Reproduce**
Install esp-idf tools

**Espressif-IDE Product Information:**
Operating System: windows 7
Java Runtime Version: 11.0.17+8-LTS
Eclipse Version: 4.25.0.v20220831-1800
Eclipse CDT Version: 10.7.1.202208160035
IDF Eclipse Plugin Version: 2.7.0.202211101524
Please use idf.py only in an ESP-IDF shell environment.
Python set for IDF_PYTHON_ENV: Python 3.9.16

Espressif > Product Information (Copy content from the console and attach as a file)

**Eclipse Error log:** 
Window > Show View > Other > Search for "Error Log" (Attach as a file)

Please attach the error log as described here https://github.com/espressif/idf-eclipse-plugin#error-log

**Comment by sigmaaa** [comment]
Hi @jotisk,

thank you for reporting this issue. Unfortunately, I couldn't reproduce this issue oт my environments, but I found a similar issue reported:
`raise RuntimeError('supported_targets for tool %s is not a list of strings' % tool_name)
RuntimeError: supported_targets for tool xtensa-esp32-elf is not a list of strings`

the same issue was mentioned [here](https://github.com/espressif/idf-eclipse-plugin/issues/612#issuecomment-1298287078). Most probably something went wrong during the esp-idf installation, so you can try to delete the .espressif folder, delete esp-idf and install esp-idf and tools from the eclipse again: 
Espressif -> Download and Configure ESP-IDF 

![](https://user-images.githubusercontent.com/24419842/198245682-c2333f98-77cb-4b75-9ba4-13d7cd6dc34b.png)

Let me know if it helps. Thank you

**Comment by jotisk** [comment]
Hi @sigmaaa, 
thank you for tip, I already tried every single occurence of this problem and its solution but non are applicable, I cannot nuke system now to make clean install. On system is installed old eclipse with ESP-IDF3. but new eclipse should have own paths so they should not collide. I tried also to instal expressif IDE (branded eclipse) to have out of box solution to eliminate any problems but is causing same error.

**Comment by GTCLive** [comment]
Same problem. Downloading tools consistently fails at 97%
**Workaround:** Manually downloading them and placing them into the local dist folder that Eclipse source them from. 

![esp_tools](https://user-images.githubusercontent.com/91785220/212464671-e8f3e06e-e94f-4180-b440-fa54824cce20.jpg)

![esp_tools2](https://user-images.githubusercontent.com/91785220/212464706-0ca15fc4-7fc3-4cda-9e48-f19e54b53704.jpg)

**Comment by sigmaaa** [comment]
Hi @GTCLive,
looks like a mirror issue for this tool. Did you manage to install the tools after a while?

**Comment by jotisk** [comment]
Hi @GTCLive , 
I have no problem with downloading, problem happens during installation. 
Till now I had no luck with solution, at moment waiting for new PC with WIN10 to test in fresh env.

**Comment by GTCLive** [comment]
Hello @sigmaaa 

Yes, dwloads still fails however I am 100% up to speed. Workaround for me is to manually download the tools using the given URLs from the error log, and copy those files into the local dist folder that eclipse sources the tools from. All tools installs fine when tools are stored local, and so having no issues at all and productive.

As @jotisk mentioned this may be related to other conflicting issues and so I'll eventually try a clean install too. I'll report if this is a persistent issue. I doubt it is an global issue though, we'd be many reporting the same. Let's see. 

Appreciate the time you're talking and the efforts that goes into this. Thank you!

**Comment by Davit-shirak** [comment]
EIM UI not working with old versions of idf. "eim install -i v4.3" command give the same error:

> INFO - Retry 3/3 for https://dl.espressif.com/dl/esp-idf/espidf.constraints.v4.3.txt in 4.0s
> WARN - Download attempt 3/3 failed for https://dl.espressif.com/dl/esp-idf/espidf.constraints.v4.3.txt: HTTP error: 404 Not Found
> ERROR - Failed to download constraints file: HTTP error: 404 Not Found
