### ISSUE TITLE
Another - "No Toolchain found for Target esp32" (IEP-158)

### ISSUE THREAD

**Issue by enjoyneering** [espressif/idf-eclipse-plugin#71]
I've look through similar issues described [here](https://github.com/espressif/idf-eclipse-plugin/issues/22). I guess problem is python. For some reason "Espressif IDF Tools" doesn't create "idf4.0_py3.7_env" folder & environment variable "IDF_PYTHON_ENV_PATH". I tried v3.8 x32 & v3.7.7 x32 same "virtualenv" log error:
 
Installing tools...
This can take a while. Please be patient.
Executing C:\Programming\Python\Python37-32\pythonw.exe C:\Programming\esp-idf-v4.0\tools\idf_tools.py install all
Installing tools: xtensa-esp32-elf, esp32ulp-elf, cmake, openocd-esp32, mconf, ninja, idf-exe, ccache
Skipping xtensa-esp32-elf@esp-2019r2-8.2.0 (already installed)
Skipping esp32ulp-elf@2.28.51.20170517 (already installed)
Skipping cmake@3.13.4 (already installed)
Skipping openocd-esp32@v0.10.0-esp32-20190313 (already installed)
Skipping mconf@v4.6.0.0-idf-20190628 (already installed)
Skipping ninja@1.9.0 (already installed)
Skipping idf-exe@1.0.1 (already installed)
Skipping ccache@3.7 (already installed)

virtualenv: error: unrecognized arguments: --no-site-packages
Creating a new Python environment in C:\Users\Acer\.espressif\python_env\idf4.0_py3.7_env
Traceback (most recent call last):
  File "C:\Programming\esp-idf-v4.0\tools\idf_tools.py", line 1372, in <module>
    main(sys.argv[1:])
  File "C:\Programming\esp-idf-v4.0\tools\idf_tools.py", line 1368, in main
    action_func(args)
  File "C:\Programming\esp-idf-v4.0\tools\idf_tools.py", line 1184, in action_install_python_env
    stdout=sys.stdout, stderr=sys.stderr)
  File "C:\Programming\Python\Python37-32\lib\subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Programming\\Python\\Python37-32\\pythonw.exe', '-m', 'virtualenv', '--no-site-packages', 'C:\\Users\\Acer\\.espressif\\python_env\\idf4.0_py3.7_env']' returned non-zero exit status 2.

**Comment by enjoyneering** [comment]
Well, I used this [thread](https://github.com/espressif/esp-idf/issues/4744) and downgrade virtualenv package:

python -m pip install --upgrade virtualenv==16.7.9

Deleted .espressif folder & rerun "Espressif IDF Tools" without any errors.

I spent 2 hours just digging forums and installing the toolchain. Good job Espressif!!!
